apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller
spec:
  serviceName: controller
  replicas: 1
  selector:
    matchLabels:
      app: controller-app
  template:
    metadata:
      labels:
        app: controller-app
    spec:
      containers:
        - name: controller-app
          image: rlmariz/remote-learning-controller:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: MODBUS_HOST
              value: nodered-modbus.default.svc.cluster.local
            - name: MODBUS_PORT
              value: '5502'
---
apiVersion: v1
kind: Service
metadata:
  name: controller-service
spec:
  selector:
    app: controller-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
