name: remote-learning

services:
  nodered:
      image: rlmariz/remote-learning-nodered:ts-0.3
      container_name: nodered      
      hostname: nodered
      restart: unless-stopped
      ports:
        - 1880:1880
        - 502:502
      environment:
        MODBUS_HOST: nodered
        MODBUS_PORT: 502
  supervisory:
      image: rlmariz/remote-learning-supervisory:ts-0.3
      container_name: supervisory
      hostname: supervisory
      restart: unless-stopped
      ports:
        - 3000:3000
      environment:
        MODBUS_HOST: nodered
        MODBUS_PORT: 502        
      depends_on:
        - nodered
      links:
        - nodered:nodered
  controller:
      image: rlmariz/remote-learning-controller:ts-0.3
      container_name: controller
      hostname: controller
      restart: unless-stopped
      ports:
        - 8000:8000
      environment:
        MODBUS_HOST: nodered
        MODBUS_PORT: 502        
      depends_on:
        - nodered
        - supervisory
      links:
        - nodered:nodered