version: "3.9"
services:
    auth:
        image: nodered/node-red:latest
        environment:
            - TZ=America/Sao_Paulo
        ports:
            - "1880:1880"
        container_name: virtual-lab
        hostname: virtuallab
        restart: unless-stopped
        networks:
            - node-red-net
        volumes:
            - node-red-data:/data
            - "./nodes:/node-red-contrib-virtual-lab"

volumes:
  node-red-data:

networks:
  node-red-net: