version: '3.4'

services:
  node-red:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./nodes:/usr/src/node-red/nodes
      - ./node_red_data:/data
      - ./package.json:/usr/src/node-red/package.json
      - ./nodemon.json:/usr/src/node-red/nodemon.json
      - ./nodes/intelligentcontrol:/data/node_modules/red-contrib-remotelearn-intelligentcontrol
      # - ./entrypoint.sh:/usr/src/node-red/entrypoint.sh
    ports:
      - 1880:1880
      - 9229:9229
    #command: [ "npm", "start" ]
    # entrypoint:
      # [
      #   "sh",
      #   "-c",
      #   "npm install ./nodes/intelligentcontrol/",
      #   "&&",
      #   "npm",
      #   "start"
      # ]
    #entrypoint: ["npm", "start"]
